# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  build-on-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # See CONTRIBUTING.md on JDK 11 build requirement
        java: [ '11' ]
        architecture: [ 'x64' ] # ubuntu-latest has no support for x86
        distribution: [ 'zulu', 'adopt' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          distribution: ${{ matrix.distribution }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
  build-on-macos:
    strategy:
      matrix:
        os: [ macos-latest ]
        # See CONTRIBUTING.md on JDK 11 build requirement
        java: [ '11' ]
        # MacOS has no support for x86 ("Error: No valid download found for version 11.x and package jdk.")
        architecture: [ 'x64' ]
        distribution: [ 'zulu', 'adopt' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          distribution: ${{ matrix.distribution }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
  build-on-windows:
    strategy:
      matrix:
        os: [ windows-latest ]
        # See CONTRIBUTING.md on JDK 11 build requirement
        java: [ '11' ]
        architecture: [ 'x86', 'x64' ]
        distribution: [ 'zulu', 'adopt' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          distribution: ${{ matrix.distribution }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build